(ns cerebras_wafer.actor-test
  "Contract test for the cerebras_wafer-compat L4 actor (Clojure / kotoba-Datom).
  Runs on bb / clojure with classpath = src:tests. Generated by
  70-tools/scaffold_wave11_clj_datomic.py."
  (:require [clojure.test :refer [deftest is testing run-tests]]
            [clojure.string :as str]
            [cerebras_wafer.actor :as a]))

(def ENTITIES ["WaferEngine" "ProcessingElement" "Fabric" "MemoryBank" "Kernel" "WaferJob"])

(deftest schema-has-all-entities
  (doseq [e ENTITIES]
    (is (some (fn [d] (str/starts-with? (str (:db/ident d)) (str ":cerebras_wafer." e "/"))) a/schema)
        (str "schema missing entity " e))))

(deftest entities-set-complete
  (is (= (set ENTITIES) a/entities)))

(deftest crud-roundtrip
  (testing "WaferEngine create/get/list/update/delete over in-memory Datom log"
    (let [port (a/in-memory-datom)
          rec  (a/create-wafer-engine port {:name "x" :generation "x"})]
      (is (string? (:db/id rec)) "create returns a :db/id")
      (is (= rec (a/get-wafer-engine port (:db/id rec))) "get round-trips the record")
      (is (= 1 (:total (a/list-wafer-engines port))) "list total counts the created record")
      (let [up (a/update-wafer-engine port (:db/id rec) {:name "updated"})]
        (is (= "updated" (get up :cerebras_wafer.WaferEngine/name)) "update applies the changed field"))
      (a/delete-wafer-engine port (:db/id rec))
      (is (= 0 (:total (a/list-wafer-engines port))) "delete removes the record"))))

(deftest list-filter-and-paginate
  (testing "L4 list surface: filtering + cursor pagination"
    (let [port (a/in-memory-datom)
          _ (a/create-wafer-engine port {:name "x" :generation "x"})
          _ (a/create-wafer-engine port {:name "y" :generation "x"})]
      (is (= 2 (:total (a/list-wafer-engines port))) "both records listed")
      (is (true? (:has-more (a/list-wafer-engines port {:limit 1}))) "limit drives has-more")
      (is (= 1 (:count (a/list-wafer-engines port {:limit 1}))) "limit caps the page")
      (is (= 1 (:total (a/list-wafer-engines port {:filter {:cerebras_wafer.WaferEngine/name "x"}})))
          "filter narrows to the matching record"))))

(deftest validation-rejects-missing-required
  (is (thrown? #?(:clj clojure.lang.ExceptionInfo :cljs cljs.core/ExceptionInfo)
               (a/create-wafer-engine (a/in-memory-datom) {}))
      "create with no required fields throws"))

;; every entity collection (not just the first) → full lifecycle via dispatch
(def SAMPLES {"waferengines" {:name "x" :generation "x"}
   "processingelements" {:dataflow "x" :flops "x"}
   "fabrics" {:topology "x" :bisectionBwTbps "x"}
   "memorybanks" {:sizeGb "x" :bandwidthTbps "x"}
   "kernels" {:name "x" :tiles "x"}
   "waferjobs" {:model "x" :tokensPerSec "x"}})

(deftest all-collections-crud
  (testing "every entity collection runs the full lifecycle through dispatch"
    (doseq [[coll sample] SAMPLES]
      (let [port    (a/in-memory-datom)
            base    (str "/v1/" coll)
            created (a/dispatch port {:method :post :path base :body sample})
            id      (get-in created [:body :db/id])]
        (is (= 201 (:status created)) (str coll " POST → 201"))
        (is (string? id) (str coll " create body carries :db/id"))
        (is (= 200 (:status (a/dispatch port {:method :get :path (str base "/" id)})))
            (str coll " GET one → 200"))
        (is (= 1 (get-in (a/dispatch port {:method :get :path base}) [:body :total]))
            (str coll " list total 1"))
        (is (= 200 (:status (a/dispatch port {:method :delete :path (str base "/" id)})))
            (str coll " DELETE → 200"))
        (is (= 0 (get-in (a/dispatch port {:method :get :path base}) [:body :total]))
            (str coll " empty after delete"))))))

(deftest dispatch-end-to-end
  (testing "runnable service surface: create→get→list→update→delete through dispatch"
    (let [port (a/in-memory-datom)
          base "/v1/waferengines"
          created (a/dispatch port {:method :post :path base :body {:name "x" :generation "x"}})
          id (get-in created [:body :db/id])]
      (is (= 201 (:status created)) "POST creates → 201")
      (is (string? id) "create body carries :db/id")
      (is (= 200 (:status (a/dispatch port {:method :get :path (str base "/" id)}))) "GET one → 200")
      (is (= 1 (get-in (a/dispatch port {:method :get :path base}) [:body :total])) "GET list → total 1")
      (is (= 404 (:status (a/dispatch port {:method :get :path (str base "/nope")}))) "GET absent → 404")
      (let [upd (a/dispatch port {:method :patch :path (str base "/" id) :body {:name "updated"}})]
        (is (= 200 (:status upd)) "PATCH → 200")
        (is (= "updated" (get-in upd [:body :cerebras_wafer.WaferEngine/name])) "PATCH applies the field"))
      (is (= 200 (:status (a/dispatch port {:method :delete :path (str base "/" id)}))) "DELETE → 200")
      (is (= 0 (get-in (a/dispatch port {:method :get :path base}) [:body :total])) "list empty after delete")
      (is (= 404 (:status (a/dispatch port {:method :get :path "/v1/bogus"}))) "unknown collection → 404"))))

(deftest expand-arity-ok
  (is (nil? (a/get-wafer-engine (a/in-memory-datom) "missing" {:expand #{}}))
      "get with :expand opts returns nil for an absent id"))

(defn -main [& _]
  (let [{:keys [fail error]} (run-tests 'cerebras_wafer.actor-test)]
    (System/exit (if (pos? (+ (or fail 0) (or error 0))) 1 0))))
