(ns cerebras_wafer.actor
  "cerebras_wafer clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). Wafer-scale AI accelerator design.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; WaferEngine
   {:db/ident :cerebras_wafer.WaferEngine/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cerebras_wafer.WaferEngine/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.WaferEngine/generation :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.WaferEngine/coreCount :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.WaferEngine/sramGb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.WaferEngine/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.WaferEngine/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; ProcessingElement
   {:db/ident :cerebras_wafer.ProcessingElement/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cerebras_wafer.ProcessingElement/engineId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.ProcessingElement/dataflow :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.ProcessingElement/flops :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.ProcessingElement/localSramKb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.ProcessingElement/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.ProcessingElement/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Fabric
   {:db/ident :cerebras_wafer.Fabric/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cerebras_wafer.Fabric/engineId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.Fabric/topology :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.Fabric/bisectionBwTbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.Fabric/latencyNs :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.Fabric/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.Fabric/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; MemoryBank
   {:db/ident :cerebras_wafer.MemoryBank/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cerebras_wafer.MemoryBank/engineId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.MemoryBank/sizeGb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.MemoryBank/bandwidthTbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.MemoryBank/kind :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.MemoryBank/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.MemoryBank/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Kernel
   {:db/ident :cerebras_wafer.Kernel/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cerebras_wafer.Kernel/engineId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.Kernel/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.Kernel/tiles :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.Kernel/occupancy :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.Kernel/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.Kernel/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; WaferJob
   {:db/ident :cerebras_wafer.WaferJob/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :cerebras_wafer.WaferJob/engineId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.WaferJob/model :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.WaferJob/tokensPerSec :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.WaferJob/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.WaferJob/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :cerebras_wafer.WaferJob/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"WaferEngine" "ProcessingElement" "Fabric" "MemoryBank" "Kernel" "WaferJob"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "cerebras_wafer: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "cerebras_wafer: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "cerebras_wafer: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── WaferEngine ────────────────────────────────────────────────────────────────
(defn create-wafer-engine
  "Create a WaferEngine."
  [port data]
  (require-fields data ["name" "generation"])
  (let [id (new-id "cs_waf")
        e {:db/id id
           :cerebras_wafer.WaferEngine/id id
           :cerebras_wafer.WaferEngine/name (get data :name)
           :cerebras_wafer.WaferEngine/generation (get data :generation)
           :cerebras_wafer.WaferEngine/coreCount (as-long (get data :coreCount))
           :cerebras_wafer.WaferEngine/sramGb (as-long (get data :sramGb))
           :cerebras_wafer.WaferEngine/createdAt (now)
           :cerebras_wafer.WaferEngine/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-wafer-engines
  "List WaferEngine with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-wafer-engines port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cerebras_wafer.WaferEngine/id))
         rows (apply-filters rows (:filter opts) [:cerebras_wafer.WaferEngine/name :cerebras_wafer.WaferEngine/generation :cerebras_wafer.WaferEngine/coreCount :cerebras_wafer.WaferEngine/sramGb])]
     (paginate rows opts))))

(defn get-wafer-engine
  "Retrieve a WaferEngine by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-wafer-engine port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-wafer-engine
  "Update a WaferEngine; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :cerebras_wafer.WaferEngine/name (get data :name)]))
                   (cond-> (contains? data :generation) (conj [:db/add id :cerebras_wafer.WaferEngine/generation (get data :generation)]))
                   (cond-> (contains? data :coreCount) (conj [:db/add id :cerebras_wafer.WaferEngine/coreCount (as-long (get data :coreCount))]))
                   (cond-> (contains? data :sramGb) (conj [:db/add id :cerebras_wafer.WaferEngine/sramGb (as-long (get data :sramGb))]))
                   (conj [:db/add id :cerebras_wafer.WaferEngine/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-wafer-engine
  "Delete a WaferEngine."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── ProcessingElement ────────────────────────────────────────────────────────────────
(defn create-processing-element
  "Create a ProcessingElement."
  [port data]
  (require-fields data ["dataflow" "flops"])
  (let [id (new-id "cs_pro")
        e {:db/id id
           :cerebras_wafer.ProcessingElement/id id
           :cerebras_wafer.ProcessingElement/engineId (get data :engineId)
           :cerebras_wafer.ProcessingElement/dataflow (get data :dataflow)
           :cerebras_wafer.ProcessingElement/flops (as-double (get data :flops))
           :cerebras_wafer.ProcessingElement/localSramKb (as-long (get data :localSramKb))
           :cerebras_wafer.ProcessingElement/createdAt (now)
           :cerebras_wafer.ProcessingElement/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-processing-elements
  "List ProcessingElement with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-processing-elements port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cerebras_wafer.ProcessingElement/id))
         rows (apply-filters rows (:filter opts) [:cerebras_wafer.ProcessingElement/engineId :cerebras_wafer.ProcessingElement/dataflow :cerebras_wafer.ProcessingElement/flops :cerebras_wafer.ProcessingElement/localSramKb])]
     (paginate rows opts))))

(defn get-processing-element
  "Retrieve a ProcessingElement by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-processing-element port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-processing-element
  "Update a ProcessingElement; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :engineId) (conj [:db/add id :cerebras_wafer.ProcessingElement/engineId (get data :engineId)]))
                   (cond-> (contains? data :dataflow) (conj [:db/add id :cerebras_wafer.ProcessingElement/dataflow (get data :dataflow)]))
                   (cond-> (contains? data :flops) (conj [:db/add id :cerebras_wafer.ProcessingElement/flops (as-double (get data :flops))]))
                   (cond-> (contains? data :localSramKb) (conj [:db/add id :cerebras_wafer.ProcessingElement/localSramKb (as-long (get data :localSramKb))]))
                   (conj [:db/add id :cerebras_wafer.ProcessingElement/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-processing-element
  "Delete a ProcessingElement."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Fabric ────────────────────────────────────────────────────────────────
(defn create-fabric
  "Create a Fabric."
  [port data]
  (require-fields data ["topology" "bisectionBwTbps"])
  (let [id (new-id "cs_fab")
        e {:db/id id
           :cerebras_wafer.Fabric/id id
           :cerebras_wafer.Fabric/engineId (get data :engineId)
           :cerebras_wafer.Fabric/topology (get data :topology)
           :cerebras_wafer.Fabric/bisectionBwTbps (as-double (get data :bisectionBwTbps))
           :cerebras_wafer.Fabric/latencyNs (as-double (get data :latencyNs))
           :cerebras_wafer.Fabric/createdAt (now)
           :cerebras_wafer.Fabric/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-fabrics
  "List Fabric with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-fabrics port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cerebras_wafer.Fabric/id))
         rows (apply-filters rows (:filter opts) [:cerebras_wafer.Fabric/engineId :cerebras_wafer.Fabric/topology :cerebras_wafer.Fabric/bisectionBwTbps :cerebras_wafer.Fabric/latencyNs])]
     (paginate rows opts))))

(defn get-fabric
  "Retrieve a Fabric by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-fabric port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-fabric
  "Update a Fabric; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :engineId) (conj [:db/add id :cerebras_wafer.Fabric/engineId (get data :engineId)]))
                   (cond-> (contains? data :topology) (conj [:db/add id :cerebras_wafer.Fabric/topology (get data :topology)]))
                   (cond-> (contains? data :bisectionBwTbps) (conj [:db/add id :cerebras_wafer.Fabric/bisectionBwTbps (as-double (get data :bisectionBwTbps))]))
                   (cond-> (contains? data :latencyNs) (conj [:db/add id :cerebras_wafer.Fabric/latencyNs (as-double (get data :latencyNs))]))
                   (conj [:db/add id :cerebras_wafer.Fabric/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-fabric
  "Delete a Fabric."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── MemoryBank ────────────────────────────────────────────────────────────────
(defn create-memory-bank
  "Create a MemoryBank."
  [port data]
  (require-fields data ["sizeGb" "bandwidthTbps"])
  (let [id (new-id "cs_mem")
        e {:db/id id
           :cerebras_wafer.MemoryBank/id id
           :cerebras_wafer.MemoryBank/engineId (get data :engineId)
           :cerebras_wafer.MemoryBank/sizeGb (as-long (get data :sizeGb))
           :cerebras_wafer.MemoryBank/bandwidthTbps (as-double (get data :bandwidthTbps))
           :cerebras_wafer.MemoryBank/kind (get data :kind)
           :cerebras_wafer.MemoryBank/createdAt (now)
           :cerebras_wafer.MemoryBank/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-memory-banks
  "List MemoryBank with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-memory-banks port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cerebras_wafer.MemoryBank/id))
         rows (apply-filters rows (:filter opts) [:cerebras_wafer.MemoryBank/engineId :cerebras_wafer.MemoryBank/sizeGb :cerebras_wafer.MemoryBank/bandwidthTbps :cerebras_wafer.MemoryBank/kind])]
     (paginate rows opts))))

(defn get-memory-bank
  "Retrieve a MemoryBank by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-memory-bank port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-memory-bank
  "Update a MemoryBank; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :engineId) (conj [:db/add id :cerebras_wafer.MemoryBank/engineId (get data :engineId)]))
                   (cond-> (contains? data :sizeGb) (conj [:db/add id :cerebras_wafer.MemoryBank/sizeGb (as-long (get data :sizeGb))]))
                   (cond-> (contains? data :bandwidthTbps) (conj [:db/add id :cerebras_wafer.MemoryBank/bandwidthTbps (as-double (get data :bandwidthTbps))]))
                   (cond-> (contains? data :kind) (conj [:db/add id :cerebras_wafer.MemoryBank/kind (get data :kind)]))
                   (conj [:db/add id :cerebras_wafer.MemoryBank/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-memory-bank
  "Delete a MemoryBank."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Kernel ────────────────────────────────────────────────────────────────
(defn create-kernel
  "Create a Kernel."
  [port data]
  (require-fields data ["name" "tiles"])
  (let [id (new-id "cs_ker")
        e {:db/id id
           :cerebras_wafer.Kernel/id id
           :cerebras_wafer.Kernel/engineId (get data :engineId)
           :cerebras_wafer.Kernel/name (get data :name)
           :cerebras_wafer.Kernel/tiles (as-long (get data :tiles))
           :cerebras_wafer.Kernel/occupancy (as-double (get data :occupancy))
           :cerebras_wafer.Kernel/createdAt (now)
           :cerebras_wafer.Kernel/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-kernels
  "List Kernel with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-kernels port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cerebras_wafer.Kernel/id))
         rows (apply-filters rows (:filter opts) [:cerebras_wafer.Kernel/engineId :cerebras_wafer.Kernel/name :cerebras_wafer.Kernel/tiles :cerebras_wafer.Kernel/occupancy])]
     (paginate rows opts))))

(defn get-kernel
  "Retrieve a Kernel by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-kernel port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-kernel
  "Update a Kernel; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :engineId) (conj [:db/add id :cerebras_wafer.Kernel/engineId (get data :engineId)]))
                   (cond-> (contains? data :name) (conj [:db/add id :cerebras_wafer.Kernel/name (get data :name)]))
                   (cond-> (contains? data :tiles) (conj [:db/add id :cerebras_wafer.Kernel/tiles (as-long (get data :tiles))]))
                   (cond-> (contains? data :occupancy) (conj [:db/add id :cerebras_wafer.Kernel/occupancy (as-double (get data :occupancy))]))
                   (conj [:db/add id :cerebras_wafer.Kernel/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-kernel
  "Delete a Kernel."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── WaferJob ────────────────────────────────────────────────────────────────
(defn create-wafer-job
  "Create a WaferJob."
  [port data]
  (require-fields data ["model" "tokensPerSec"])
  (let [id (new-id "cs_waf")
        e {:db/id id
           :cerebras_wafer.WaferJob/id id
           :cerebras_wafer.WaferJob/engineId (get data :engineId)
           :cerebras_wafer.WaferJob/model (get data :model)
           :cerebras_wafer.WaferJob/tokensPerSec (as-double (get data :tokensPerSec))
           :cerebras_wafer.WaferJob/status (get data :status)
           :cerebras_wafer.WaferJob/createdAt (now)
           :cerebras_wafer.WaferJob/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-wafer-jobs
  "List WaferJob with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-wafer-jobs port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :cerebras_wafer.WaferJob/id))
         rows (apply-filters rows (:filter opts) [:cerebras_wafer.WaferJob/engineId :cerebras_wafer.WaferJob/model :cerebras_wafer.WaferJob/tokensPerSec :cerebras_wafer.WaferJob/status])]
     (paginate rows opts))))

(defn get-wafer-job
  "Retrieve a WaferJob by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-wafer-job port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-wafer-job
  "Update a WaferJob; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :engineId) (conj [:db/add id :cerebras_wafer.WaferJob/engineId (get data :engineId)]))
                   (cond-> (contains? data :model) (conj [:db/add id :cerebras_wafer.WaferJob/model (get data :model)]))
                   (cond-> (contains? data :tokensPerSec) (conj [:db/add id :cerebras_wafer.WaferJob/tokensPerSec (as-double (get data :tokensPerSec))]))
                   (cond-> (contains? data :status) (conj [:db/add id :cerebras_wafer.WaferJob/status (get data :status)]))
                   (conj [:db/add id :cerebras_wafer.WaferJob/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-wafer-job
  "Delete a WaferJob."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/waferengines" :op :create :entity "WaferEngine"}
   {:method "GET" :path "/v1/waferengines" :op :list :entity "WaferEngine"}
   {:method "GET" :path "/v1/waferengines/:id" :op :get :entity "WaferEngine"}
   {:method "PATCH" :path "/v1/waferengines/:id" :op :update :entity "WaferEngine"}
   {:method "DELETE" :path "/v1/waferengines/:id" :op :delete :entity "WaferEngine"}
   {:method "POST" :path "/v1/processingelements" :op :create :entity "ProcessingElement"}
   {:method "GET" :path "/v1/processingelements" :op :list :entity "ProcessingElement"}
   {:method "GET" :path "/v1/processingelements/:id" :op :get :entity "ProcessingElement"}
   {:method "PATCH" :path "/v1/processingelements/:id" :op :update :entity "ProcessingElement"}
   {:method "DELETE" :path "/v1/processingelements/:id" :op :delete :entity "ProcessingElement"}
   {:method "POST" :path "/v1/fabrics" :op :create :entity "Fabric"}
   {:method "GET" :path "/v1/fabrics" :op :list :entity "Fabric"}
   {:method "GET" :path "/v1/fabrics/:id" :op :get :entity "Fabric"}
   {:method "PATCH" :path "/v1/fabrics/:id" :op :update :entity "Fabric"}
   {:method "DELETE" :path "/v1/fabrics/:id" :op :delete :entity "Fabric"}
   {:method "POST" :path "/v1/memorybanks" :op :create :entity "MemoryBank"}
   {:method "GET" :path "/v1/memorybanks" :op :list :entity "MemoryBank"}
   {:method "GET" :path "/v1/memorybanks/:id" :op :get :entity "MemoryBank"}
   {:method "PATCH" :path "/v1/memorybanks/:id" :op :update :entity "MemoryBank"}
   {:method "DELETE" :path "/v1/memorybanks/:id" :op :delete :entity "MemoryBank"}
   {:method "POST" :path "/v1/kernels" :op :create :entity "Kernel"}
   {:method "GET" :path "/v1/kernels" :op :list :entity "Kernel"}
   {:method "GET" :path "/v1/kernels/:id" :op :get :entity "Kernel"}
   {:method "PATCH" :path "/v1/kernels/:id" :op :update :entity "Kernel"}
   {:method "DELETE" :path "/v1/kernels/:id" :op :delete :entity "Kernel"}
   {:method "POST" :path "/v1/waferjobs" :op :create :entity "WaferJob"}
   {:method "GET" :path "/v1/waferjobs" :op :list :entity "WaferJob"}
   {:method "GET" :path "/v1/waferjobs/:id" :op :get :entity "WaferJob"}
   {:method "PATCH" :path "/v1/waferjobs/:id" :op :update :entity "WaferJob"}
   {:method "DELETE" :path "/v1/waferjobs/:id" :op :delete :entity "WaferJob"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"waferengines" {:create create-wafer-engine :list list-wafer-engines :get get-wafer-engine :update update-wafer-engine :delete delete-wafer-engine}
   "processingelements" {:create create-processing-element :list list-processing-elements :get get-processing-element :update update-processing-element :delete delete-processing-element}
   "fabrics" {:create create-fabric :list list-fabrics :get get-fabric :update update-fabric :delete delete-fabric}
   "memorybanks" {:create create-memory-bank :list list-memory-banks :get get-memory-bank :update update-memory-bank :delete delete-memory-bank}
   "kernels" {:create create-kernel :list list-kernels :get get-kernel :update update-kernel :delete delete-kernel}
   "waferjobs" {:create create-wafer-job :list list-wafer-jobs :get get-wafer-job :update update-wafer-job :delete delete-wafer-job}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "cerebras_wafer-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
